-- local util = require('config.util')
--
-- -- Colorscheme + transparent bg on enter
-- vim.api.nvim_create_autocmd('VimEnter', {
--   callback = function()
--     vim.cmd.colorscheme 'gruvbox'
--     util.set_transparent()
--   end,
-- })
--
-- -- Yank highlight
-- vim.api.nvim_create_autocmd('TextYankPost', {
--   desc     = 'Highlight on yank',
--   group    = vim.api.nvim_create_augroup('kickstart-highlight-yank', { clear = true }),
--   callback = function() vim.hl.on_yank() end,
-- })
